ALU/src/Mux_2x1.v
DataPath/src/Reg_Simple.v
DataPath/src/Sign_Extend.v
DataPath/src/Reg_D.v
DataPath/src/Mux_4x1.v
DataPath/src/Reg_Enable.v
DataPath/src/Left_Shift.v
DataPath/src/Data_Path.v
DataPath/src/tb/Data_Path_TB.v
MemorySystem/src/Memory_MUX.v
MemorySystem/src/Instruction_Decoder.v
MemorySystem/src/Memory_System.v
MemorySystem/src/ROM/Program_Memory.v
MemorySystem/src/text.dat
MemorySystem/src/Priority_Decoder.v
MemorySystem/src/RAM/Data_Memory.v
RegisterFile/src/encoder_32.v
RegisterFile/src/ff_d.v
RegisterFile/src/Register_File.v
RegisterFile/src/mux_32.v
